# Generated by Django 3.2.9 on 2021-12-02 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('category', models.CharField(blank=True, choices=[('Fruits', 'Fruits'), ('Vagetable', 'Vagetable'), ('Oil', 'Oil'), ('Rice', 'Rice'), ('Others', 'Others')], max_length=60, null=True)),
                ('name', models.CharField(max_length=100)),
                ('price', models.DecimalField(decimal_places=2, max_digits=8)),
                ('image', models.ImageField(upload_to='products')),
                ('description', models.TextField()),
                ('date_added', models.DateField(auto_now_add=True)),
            ],
        ),
    ]
