# Generated by Django 3.2.9 on 2021-12-02 20:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0005_product_user'),
    ]

    operations = [
        migrations.AlterField(
            model_name='product',
            name='qunatity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
