# Generated by Django 3.2.9 on 2021-12-02 23:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('home', '0009_alter_bid_timestamp'),
    ]

    operations = [
        migrations.AddField(
            model_name='bid',
            name='quantity',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
